src/Entity/Conges.php
<?php

namespace App\Entity;

use App\Repository\CongesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\PseudoTypes\True_;

#[ORM\Entity(repositoryClass: CongesRepository::class)]
class Conges
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\Column]
    private ?bool $estValide = null;

    #[ORM\ManyToOne(inversedBy: 'conges')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $ref_pilote = null;

    #[ORM\ManyToOne(inversedBy: 'congesValideAdmin')]
    #[ORM\JoinColumn(nullable: True)]
    private ?Utilisateur $ref_validation_admin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function isEstValide(): ?bool
    {
        return $this->estValide;
    }

    public function setEstValide(bool $estValide): static
    {
        $this->estValide = $estValide;

        return $this;
    }

    public function getRefPilote(): ?Utilisateur
    {
        return $this->ref_pilote;
    }

    public function setRefPilote(?Utilisateur $ref_pilote): static
    {
        $this->ref_pilote = $ref_pilote;

        return $this;
    }

    public function getRefValidationAdmin(): ?Utilisateur
    {
        return $this->ref_validation_admin;
    }

    public function setRefValidationAdmin(?Utilisateur $ref_validation_admin): static
    {
        $this->ref_validation_admin = $ref_validation_admin;

        return $this;
    }
}

src/Form/CongesType.php
<?php

namespace App\Form;

use App\Entity\Conges;
use App\Entity\Utilisateur;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CongesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('dateDebut',DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('dateFin',DateType::class, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Conges::class,
        ]);
    }
}

src/Controller/CongesController.php
<?php

namespace App\Controller;

use App\Entity\Conges;
use App\Form\CongesEditType;
use App\Form\CongesType;
use App\Repository\CongesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/conges')]
class CongesController extends AbstractController
{
    #[Route('/', name: 'app_conges_index', methods: ['GET'])]
    public function index(CongesRepository $congesRepository): Response
    {
        if (!$this->getUser() || !in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            return $this->redirectToRoute('app_home');
        }
        return $this->render('conges/index.html.twig', [
            'conges' => $congesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_conges_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        if (!$this->getUser() || !in_array('ROLE_PILOTE', $this->getUser()->getRoles()) && !in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            return $this->redirectToRoute('app_home');
        }
        $conge = new Conges();
        $form = $this->createForm(CongesType::class, $conge);
        $form->handleRequest($request);
        $conge->setRefPilote($this->getUser());
        $conge->setEstValide(false);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($conge);
            $entityManager->flush();

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('conges/new.html.twig', [
            'conge' => $conge,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_conges_show', methods: ['GET'])]
    public function show(Conges $conge): Response
    {
        if (!$this->getUser() || !in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            return $this->redirectToRoute('app_home');
        }
        return $this->render('conges/show.html.twig', [
            'conge' => $conge,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_conges_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Conges $conge, EntityManagerInterface $entityManager): Response
    {
        if (!$this->getUser() || !in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            return $this->redirectToRoute('app_home');
        }
        $form = $this->createForm(CongesEditType::class, $conge);
        $form->handleRequest($request);
        $conge->setRefValidationAdmin($this->getUser());
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_conges_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('conges/edit.html.twig', [
            'conge' => $conge,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_conges_delete', methods: ['POST'])]
    public function delete(Request $request, Conges $conge, EntityManagerInterface $entityManager): Response
    {
        if (!$this->getUser() || !in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            return $this->redirectToRoute('app_home');
        }
        if ($this->isCsrfTokenValid('delete'.$conge->getId(), $request->request->get('_token'))) {
            $entityManager->remove($conge);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_conges_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/conges/_delete_form.html.twig
<form method="post" action="{{ path('app_conges_delete', {'id': conge.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conge.id) }}">
    <button class="btn">Delete</button>
</form>

templates/conges/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/conges/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Conges{% endblock %}

{% block body %}
    {% block spinner %}
        {{ parent() }}
    {% endblock %}

    {% block navbar %}
        {{ parent() }}
    {% endblock %}
    <div class="container-xxl py-5">
        <div class="container py-5">
            <div class="row g-5 align-items-center">
                <div class="col-lg-5 wow fadeInUp" data-wow-delay="0.1s">
                    <h1>Confirmier Congés</h1>
                </div>
                <div class="col-lg-7">
                    <div class="bg-light text-center p-5 wow fadeIn" data-wow-delay="0.5s">
                        {{ include('conges/_form.html.twig', {'button_label': 'Update'}) }}
                        {{ include('conges/_delete_form.html.twig') }}
                        <a href="{{ path('app_conges_index') }}">back to list</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/conges/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conges index{% endblock %}

{% block body %}
    {% block spinner %}
        {{ parent() }}
    {% endblock %}

    {% block navbar %}
        {{ parent() }}
    {% endblock %}
    <h1>Conges index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>DateDebut</th>
                <th>DateFin</th>
                <th>EstValide</th>
                <th>Pilote</th>
                <th>Valider par</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for conge in conges %}
            <tr>
                <td>{{ conge.id }}</td>
                <td>{{ conge.dateDebut ? conge.dateFin|date('Y-m-d') : ''}}</td>
                <td>{{ conge.dateFin ? conge.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ conge.estValide ? 'Yes' : 'No' }}</td>
                <td>{{ conge.refPilote }}</td>
                <td>{{ conge.refValidationAdmin }}</td>
                <td>
                    <a href="{{ path('app_conges_show', {'id': conge.id}) }}">show</a>
                    <a href="{{ path('app_conges_edit', {'id': conge.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="container-fluid bg-dark text-light footer pt-5 wow fadeIn" data-wow-delay="0.1s" style="margin-top: 6rem;">
        <div class="container py-5">

        </div>
        <div class="container">
            <div class="copyright">
                <h4><a href="{{ path('app_admin') }}">retour</a></h4>
            </div>
        </div>
    </div>
{% endblock %}

templates/conges/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Conges{% endblock %}

{% block body %}
    {% block spinner %}
        {{ parent() }}
    {% endblock %}

    {% block navbar %}
        {{ parent() }}
    {% endblock %}
    <div class="container-xxl py-5">
        <div class="container py-5">
            <div class="row g-5 align-items-center">
                <div class="col-lg-5 wow fadeInUp" data-wow-delay="0.1s">
                    <h1>Prendre un congés</h1>
                </div>
                <div class="col-lg-7">
                    <div class="bg-light text-center p-5 wow fadeIn" data-wow-delay="0.5s">
                        {{ include('conges/_form.html.twig') }}
                        <a href="{{ path('app_home') }}">retour</a>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/conges/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conges{% endblock %}

{% block body %}
    {% block spinner %}
        {{ parent() }}
    {% endblock %}

    {% block navbar %}
        {{ parent() }}
    {% endblock %}
    <h1>Conges</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ conge.id }}</td>
            </tr>
            <tr>
                <th>DateDebut</th>
                <td>{{ conge.dateDebut ? conge.dateFin|date('Y-m-d') : ''  }}</td>
            </tr>
            <tr>
                <th>DateFin</th>
                <td>{{ conge.dateFin ? conge.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>EstValide</th>
                <td>{{ conge.estValide ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Pilote</th>
                <td>{{ conge.refPilote }}</td>
            </tr>
            <tr>
                <th>Validation par</th>
                <td>{{ conge.refValidationAdmin }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_conges_index') }}">back to list</a>

    <a href="{{ path('app_conges_edit', {'id': conge.id}) }}">edit</a>

    {{ include('conges/_delete_form.html.twig') }}
{% endblock %}